# Generated by Django 4.1.5 on 2023-06-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id_cotizacion', models.AutoField(primary_key=True, serialize=False, verbose_name='id Cotizacion')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Cliente')),
                ('telefono', models.IntegerField(max_length=9, verbose_name='Fono Cliente')),
                ('correo', models.CharField(max_length=80, verbose_name='Correo')),
                ('mensaje', models.TextField(max_length=255, verbose_name='Mensaje Cotizacion')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=50, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='userName',
            field=models.CharField(max_length=50, verbose_name='Nombre Usuario'),
        ),
    ]
