# Generated by Django 4.1.5 on 2023-06-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0003_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='static/core/img/logobueno.png', upload_to='static/core/img/'),
        ),
    ]
