# Generated by Django 4.1.5 on 2023-06-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0004_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='core/img/logobueno.png', upload_to='core/img/'),
        ),
    ]
