# Generated by Django 4.1.5 on 2023-06-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0005_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono',
            field=models.IntegerField(verbose_name='Fono Cliente'),
        ),
    ]
