# Generated by Django 4.2.2 on 2023-06-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0006_alter_cotizacion_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(default='Sin Revisar', max_length=80, verbose_name='Estado Cotizacion'),
        ),
    ]
