# Generated by Django 4.2.2 on 2023-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0007_cotizacion_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False, verbose_name='id Compra')),
                ('cantidad_producto', models.IntegerField(verbose_name='Cantidad Productos')),
                ('Precio_total', models.IntegerField(verbose_name='precio Total')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id producto'),
        ),
    ]
