# Generated by Django 4.2.2 on 2023-07-07 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mecanicosDuoc', '0008_compra_alter_producto_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad_producto',
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(verbose_name='Cantidad Productos')),
                ('precio_total', models.IntegerField(verbose_name='Precio Total')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanicosDuoc.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mecanicosDuoc.producto')),
            ],
        ),
    ]
